### ISSUE TITLE
add another gcp datasources

### ISSUE THREAD

**Issue by MikaDiablo** [hystax/optscale#194]
I already have a configured gcp datasource to access a gcp project and the billing dataset. Now i want to add the other gcp projects i have to the same datasource, so i tried to bind the service account used in the first project with the other projects after creating the list of roles in each project and i waited more than 3 hours to see if resources will be synchronized between hystax and gcp projects but nothing happened, even though there was metrics and billing imported.

So i tried to add a new datasource for the other gcp project, and when trying to connect my new datasource i have the below error:
![Design sans titre](https://github.com/hystax/optscale/assets/56795299/ae8a50b1-e7ff-4b94-8857-130731b2981a)
The connection trying to search for the dataset in the gcp project according to the given json, but my dataset is in my old gcp project that is already connected in my old datasource.

Is this a bug ? Or someone have an idea on how to add multiple gcp project while the billing dataset is only in one of them ?

**Comment by nk-hystax** [comment]
Adding multiple projects data into the same dataset don't work on current cloud account as OptScale queries expenses with datasource's project_id only. It also uses project_id while requesting your expenses, see https://github.com/hystax/optscale/blob/0478ae696f30f9bcef1244a3f9038d300ae6c702/tools/cloud_adapter/clouds/gcp.py#L648-L649

So the only workaround here is to configure separate datasets in other required projects and use them to connect new datasources.

**Comment by MikaDiablo** [comment]
Unfortunately this workaround won't work for me: duplicating the same dataset and permissions across multiple projects, especially for production environments.
The billing dataset is linked to the billing_account_id and not to a project, this workaround would work if i have a billing account per project; this is not my case. 
And according to the google documentation: https://cloud.google.com/billing/docs/how-to/export-data-bigquery-setup#project  it's recommended to have a separate project for the billing administration.

**Comment by nk-hystax** [comment]
@MikaDiablo filed a ticket for that

**Comment by klinux** [comment]
We have the same problem here.

**Comment by aswintyv** [comment]
+1 for this problem.

**Comment by stanfra** [comment]
Hello @MikaDiablo , @klinux, @aswintyv , this issue solved in https://github.com/hystax/optscale/releases/tag/2024041801-public release.

**Comment by Shikhar-Nahar** [comment]
Hi @stanfra 
There is an issue with the current implementation for this request of supporting multiple projects under same billing account.

Each project needs to be added as a separate data source in optscale, for which optscale queries the same `billing_export` bigquery table multiple times with different project.id in `where` clause.
Since the billing_export table is not partitioned or clustered by project.id this causes the query to do full scan each time it is run. For a single billing account with many projects and large number of entries the standard export can be quite large. 
<img width="449" alt="image" src="https://github.com/user-attachments/assets/24e54a02-8a31-4a06-8845-4a07dbf06837">

Since optscale queries this table multiple times each day for each data source, it makes bigquery costs go up. Ideally the same export table should only be queried once for all associated projects/datasources.
