### ISSUE TITLE
GCP Data Source is not active

### ISSUE THREAD

**Issue by mkaplan-eyesclear** [hystax/optscale#2]
Hi,
I tried to install and configure the optscale in my private GCP project. But I can not see GCP section in the "Connect Data Source" screen.
Is GCP support come with another version?

![image](https://user-images.githubusercontent.com/69202236/211935446-23b90bcd-2efe-4bae-9485-6b888cf32aa0.png)

**Comment by EdKuss** [comment]
Hi Mkaplan,

I am Ed, one of the OptScale PMs. You hit the nail on its head. GCP comes with the next version. We do support GCP (how could we not?) in our regular SaaS offering of OptScale. We started with SaaS and later added the open source avenue thus here we are a bit behind. GCP is coming in February.
In the meantime I invite you to use the SaaS version and later we just export the data to your deployment. Just go to https://hystax.com/ and sign in. 
And also pls share your feedback about the tool. This is important for us in order to improve it. Maybe you have a feature request which could be useful for other users as well. 

Rgds, 
Ed

**Comment by Spikeophant** [comment]
Following, we're a GCP user as well and found this after OSS deploy.  We'll be watching for the release next month.

**Comment by EdKuss** [comment]
Yeap, if you not want to check out the SaaS version https://my.optscale.com/ in the meantime, waiting till next month is the only thing you can do; but time goes fast (for good or for worse). Just watch this space.

**Comment by matdtr** [comment]
+1 following for GCP release. 

@mkaplan-eyesclear did you managed to install it on GKE?

**Comment by Spikeophant** [comment]
Any update?

**Comment by maxb-hystax** [comment]
GCP connection is planned for release in February, stay tuned!

**Comment by Spikeophant** [comment]
Any timeline update on the GCP connector.

**Comment by maxb-hystax** [comment]
Hi All,

We've published updated images, which include GCP support - https://github.com/hystax/optscale/commit/245f94dd7708cad6cb549d2382335def20480575

Code will be updated very soon.

Feel free to deploy/update from the new images.

**Comment by maxb-hystax** [comment]
The code is here - https://github.com/hystax/optscale/commit/35edd4277121fb73acba36bacc5ac97027b13dfe !
