### ISSUE TITLE
Optscale is not getting the GCP recommentations

### ISSUE THREAD

**Issue by gelasca** [hystax/optscale#444]
**Describe the bug**
The recommendations for GCP are not appearing.

**To Reproduce**
1. Login into Optscale platform;
2. Click on 'Recommendations' on the left navigation menu ;
4. Note that Optscale are not receiving recommendations for GCP.

**Expected behavior**
There should be recommendations just like the third following image.

**Screenshots**
![Captura de tela 2024-10-25 112611](https://github.com/user-attachments/assets/89b8237c-3a95-4da0-b606-529f388d3fa3)
![Captura de tela 2024-10-25 112619](https://github.com/user-attachments/assets/e6305fcd-3e9f-4a2c-9048-c1b9f2f99b7e)
![image](https://github.com/user-attachments/assets/c78c2bf7-2f1d-4a46-95a8-6deb32f7c5ff)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version:  130.0.6723.60 (Official Build) (64-bit) 130.0.6723.60 (Official Build) (64-bit)
 
**Additional context**
It has being more than 3 weeks that It is not working for me.

**Comment by stanfra** [comment]
Hi @gelasca , OptScale do not use recommendations from GCP, it calculates them by itself, so please verify that you have volumes that aren't attached to any instance for more then 1 day in order to appear in the recommendation. For Underutilized instances - check that you set service credentials for GCP cloud during cluster initialization in your overlay(https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml#L20-L45), OptScale uses them during this recommendation check. Also please check that performance metrics for instances are processed -  you can check them on instance details page (only for active instances) or on data source details: check in the Advanced tab and that the active resource meets the requirements you set to be included in the recommendation. If after all this the resource still does not appear in the recommendation, then please write the region and flavor of this resource so that we can take a look.
