### ISSUE TITLE
Connect GCP BigQuery Datasource to my.optscale.com

### ISSUE THREAD

**Issue by MikaDiablo** [hystax/optscale#94]
I am new to Hystax Products and optscale and i am trying to connect my gcp account so i followed the documentation:
https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html

And I got the error below

`/restapi/v2/organizations/XXXX-XXXX-XXXX-XXXX/cloud_accounts: Cloud connection error: Invalid billing type. Expected billing type to be Standard.`

The Bigquery Dataset is configured a long time ago, so is there something i missed here or it's just a temporary bug ?

**Comment by efbe2121** [comment]
Make sure you're targeting the Standard Billing Export on BigQuery not the Detailed Billing Export.

**Comment by MikaDiablo** [comment]
Yes it is the standard one.

**Comment by maxb-hystax** [comment]
Can you let us know what is the name of the table with billing export data?

**Comment by MikaDiablo** [comment]
Dataset: billing_export
Table name: gcp_billing_export_resource_v1_XXXXXXXXXX

**Comment by efbe2121** [comment]
> Dataset: billing_export Table name: gcp_billing_export_resource_v1_XXXXXXXXXX

It is not standard billing data. Check my screenshot
![image](https://github.com/hystax/optscale/assets/44221453/8fdb51c3-54f8-4e10-b644-41203170cf22)
Below without "resource" is the Standard
The one with "resource" is the Detailed

**Comment by MikaDiablo** [comment]
okay i'll redo the billing export and retry the connection, Thanks !

**Comment by mbukhori-gdp** [comment]
Hi @efbe2121, Sorry to bring this up again. I would like to ask about how to connect GCP data sources to optscale. 
I've followed this article: https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html#connecting-a-gcp-account-to-optscale and have set the billing type to Standard. But the problem is still the same, did I miss a step? 

![Image](https://github.com/user-attachments/assets/efe7efa1-e965-4151-96ed-3acbee067f08)

![Image](https://github.com/user-attachments/assets/7f47c9f5-262d-47de-b080-e0db6f7e041b)

![Image](https://github.com/user-attachments/assets/d1913e1f-c928-43cf-a9ba-1e237a358314)

Thank You

**Comment by auto-hx** [comment]
Welcome  hystax/optscale! 


You are invited to access Hystax's Customer Self Service Portal 


 By accessing this portal, you can track your requests online,

access knowledge base and join the community forums.
ACCEPT THE INVITATION



 




Your user name is ***@***.*** | You can also click here to accept the invitation 





 



Thank you, Hystax Administrator






 








This email has been sent to you&#x28;reply&#x2b;bcdweafw3xrq47lo74t2pugfxlw7fevbnhhg643z34&#x40;reply.github.com&#x29; by nsmirnov&#x40;hystax.com from Hystax. Please contact the sender&#x28;nsmirnov&#x40;hystax.com&#x29; for any clarifications.
